services:
  fastapi: # Defines a service named 'fastapi'
    image: korukonda/fastapi:dev
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
     - 8000:8000

  streamlit: # Defines a service named 'fastapi'
    image: korukonda/streamlit:dev
    build: 
        context: ./streamlit_app
        dockerfile: Dockerfile
    ports:
     - 8501:8501
    environment:
       API_URL: http://fastapi:8000




